# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171214_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
